# .travis.yml
language: go
go:
  - 1.11.4
install: true
before_install:
  - go get github.com/mch1307/gvs
  - go get github.com/mattn/goveralls
script:
  - goveralls -v -service=travis-ci
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux