# .travis.yml
language: go
go:
    - 1.11.4
install: true
sudo: required
before_install:
  - go get github.com/mattn/goveralls
script:
  - goveralls -v -service=travis-ci
after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash 